### ISSUE TITLE
Does not create logfile at initial start

### ISSUE THREAD

**Issue by infernix** [SevenW/Plugwise-2-py#1]
Minor bug, but:
```
rsync: link_stat "/var/lib/plugwise/2014/pwact/pwact-2014-08-27*.log" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1070) [sender=3.0.9]
Traceback (most recent call last):
  File "Plugwise-2.py", line 1235, in <module>
    main=PWControl()
  File "Plugwise-2.py", line 162, in __init__
    with open(self.lastlogfname, 'r+') as f:
IOError: [Errno 2] No such file or directory: u'/var/lib/plugwise/pwlastlog.log'
```
Solved by a 
```touch /var/lib/plugwise/pwlastlog.log```

**Comment by SevenW** [comment]
Finally solved by using file mode 'a+', followed by f.seek(0)
