### ISSUE TITLE
exception in join code

### ISSUE THREAD

**Issue by SevenW** [SevenW/Plugwise-2-py#10]
Traceback (most recent call last):
  File "Plugwise-2.py", line 1339, in <module>
    main.run()
  File "Plugwise-2.py", line 1210, in run
    debug("joined node table: %s" % (circleplus.read_node_table(),))
  File "/home/frank/Plugwise-2-py/plugwise/api.py", line 862, in read_node_table
    resp = self._expect_response(PlugwiseAssociatedNodesResponse, seqnr)
  File "/home/frank/Plugwise-2-py/plugwise/api.py", line 417, in _expect_response
    raise TimeoutException("Timeout while waiting for response from circle '%s'" % (self.attr['name'],))
plugwise.exceptions.TimeoutException: Timeout while waiting for response from circle 'circle+'

**Comment by SevenW** [comment]
Fixed by adding exception handling
