### ISSUE TITLE
IndexError in log_recording

### ISSUE THREAD

**Issue by infernix** [SevenW/Plugwise-2-py#37]
```
Jan 26 14:36:51 spirit python[9862]: True
Jan 26 14:36:51 spirit python[9862]: rsync -aXuq /var/lib/plugwise/2017/pwact/pwact-2017-01-26*.log /tmp/2017/pwact/
Jan 26 14:36:51 spirit python[9862]: offline
Jan 26 14:36:51 spirit python[9862]: Traceback (most recent call last):
Jan 26 14:36:51 spirit python[9862]:   File "/home/gerben/Plugwise-2-py/Plugwise-2.py", line 1457, in <module>
Jan 26 14:36:51 spirit python[9862]:     main.run()
Jan 26 14:36:51 spirit python[9862]:   File "/home/gerben/Plugwise-2-py/Plugwise-2.py", line 1414, in run
Jan 26 14:36:51 spirit python[9862]:     self.log_recording(self.controls[idx], c.mac)
Jan 26 14:36:51 spirit python[9862]:   File "/home/gerben/Plugwise-2-py/Plugwise-2.py", line 953, in log_recording
Jan 26 14:36:51 spirit python[9862]:     tdt, twatt, twatt_hour = log[-1]
Jan 26 14:36:51 spirit python[9862]: IndexError: list index out of range
```

I've added two new circles and they are running firmware 2015-09-18. I did a factory reset on them; they were used with a Sense before.

Perhaps this fails because there is no data yet due to the reset?

**Comment by SevenW** [comment]
Yes, looks like it. The specific line 953 needs exception handling. 
There could also be a problem with the firmware. I do not know whether it is compatible.

**Comment by infernix** [comment]
Doesn't seem to happen any longer and the newer firmware circle works fine, so this is likely the lack of any history in the circle causing the indexerror.
