### ISSUE TITLE
Unable to pair Circles

### ISSUE THREAD

**Issue by jjwbruijn** [SevenW/Plugwise-2-py#42]
Just bought a few second hand-circles + stick, having problems getting them to pair properly. After getting one of the circles to work with Plugwise-2-py, I figured I had to reset all the circles and rebind them. That was a very poor choice, as I've been unable to get them to talk to eachother. I've tried Join-2.py, but some kind of comms timeout occurs.

```/Plugwise-2-py# python Join-2.py
True
offline
Traceback (most recent call last):
  File "Join-2.py", line 1331, in <module>
    main.run()
  File "Join-2.py", line 1208, in run
    self.device.enable_joining(True)
  File "/home/jbruijn/Plugwise-2-py/plugwise/api.py", line 290, in enable_joining
    self.expect_response(PlugwiseAckMacResponse)
  File "/home/jbruijn/Plugwise-2-py/plugwise/api.py", line 186, in expect_response
    msg = self._recv_response(retry_timeout)
  File "/home/jbruijn/Plugwise-2-py/plugwise/api.py", line 142, in _recv_response
    raise TimeoutException("Timeout while waiting for response from device")
plugwise.exceptions.TimeoutException: Timeout while waiting for response from device
```

Any suggestions are welcome!

Setup:
pw-conf.json:
`{"static": [
{"mac": "000D6F00007293e5", "category": "misc", "name": "circle+", "loginterval": "60", "always_on": "False", "production": "False", "location": "hall"}
]}
`

pw-control.json:
`{"dynamic": [
{"mac": "000D6F00007293e5", "switch_state": "on", "name": "circle+", "schedule_state": "off", "schedule": "", "savelog": "no", "monitor": "no"}
],
"log_level": "debug",
"log_comm": "yes"}
`
pwlogger:
```2017-08-12 23:06:06,163 - pw-logger - INFO - logging started
2017-08-12 23:06:06,164 - pw-logger - INFO - MQTT client initializing for 127.0.0.1:1883
2017-08-12 23:06:06,165 - pw-logger - INFO - MQTT connected return code 0
2017-08-12 23:06:06,165 - pw-logger - DEBUG - MQTT init done
2017-08-12 23:06:06,165 - pw-logger - INFO - MQTT subscribed to plugwise2py/cmd/# with qos 0
2017-08-12 23:06:06,166 - pw-logger - INFO - MQTT thread started
2017-08-12 23:06:06,166 - pw-logger - INFO - MQTT connected return code 0
2017-08-12 23:06:06,267 - pw-logger - INFO - MQTT Subscribed: 1 (0,)
2017-08-12 23:06:07,881 - pw-logger - DEBUG - SEND   14 '\x05\x05\x03\x03000AB43C\r\n'
2017-08-12 23:06:07,889 - pw-logger - DEBUG - STRU      '--->' '0000' '0022' <data> '9B7F' '<---'
2017-08-12 23:06:07,890 - pw-logger - DEBUG - DATA    4 '00C1'
2017-08-12 23:06:07,890 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2017-08-12 23:06:07,899 - pw-logger - DEBUG - STRU      '--->' '0011' '0022' <data> '5986' '<---'
2017-08-12 23:06:07,900 - pw-logger - DEBUG - DATA   26 '0101550D6F00007293E53D55FF'
2017-08-12 23:06:07,900 - pw-logger - DEBUG - PARS      '01' EVAL '1'
2017-08-12 23:06:07,900 - pw-logger - DEBUG - PARS      '01' EVAL '1'
2017-08-12 23:06:07,900 - pw-logger - DEBUG - PARS      '550D6F00007293E5' EVAL '6128676713719305189'
2017-08-12 23:06:07,900 - pw-logger - DEBUG - PARS      '3D55' EVAL '15701'
2017-08-12 23:06:07,900 - pw-logger - DEBUG - PARS      'FF' EVAL '255'
2017-08-12 23:06:07,901 - pw-logger - DEBUG - <plugwise.protocol.PlugwiseStatusResponse object at 0x7f1e90ac6c10>
2017-08-12 23:06:07,902 - pw-logger - DEBUG - SEND   30 '\x05\x05\x03\x030023000D6F00007293E562B2\r\n'
2017-08-12 23:06:07,908 - pw-logger - DEBUG - STRU      '-->>' '0000' '0023' <data> '312E' '<---'
2017-08-12 23:06:07,909 - pw-logger - DEBUG - DATA    4 '00C1'
2017-08-12 23:06:07,909 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2017-08-12 23:06:07,927 - pw-logger - DEBUG - STRU      '--->' '0000' '0023' <data> '9B88' '<---'
2017-08-12 23:06:07,927 - pw-logger - DEBUG - DATA    4 '00E1'
2017-08-12 23:06:07,927 - pw-logger - ERROR - unexpected response [1]:'expected response code 0024, received code 0000'
2017-08-12 23:06:07,927 - pw-logger - DEBUG - STRU      '--->' '0000' '0023' <data> '9B88' '<---'
2017-08-12 23:06:07,927 - pw-logger - DEBUG - DATA    4 '00E1'
2017-08-12 23:06:07,928 - pw-logger - DEBUG - PARS      '00E1' EVAL '225'
2017-08-12 23:06:07,928 - pw-logger - DEBUG - Received an error status '00E1' from circle 'circle+' - Network slow or circle offline - Retry receive ...
2017-08-12 23:06:07,928 - pw-logger - ERROR - OFFLINE Circle 'circle+' during initialization Error: Timeout while waiting for response from circle 'circle+'
2017-08-12 23:06:07,929 - pw-logger - INFO - adding circle: circle+
2017-08-12 23:06:07,929 - pw-logger - DEBUG - mac -000D6F000076A9A3- logaddr -3083- logaddr_idx -0- logaddr_ts -0-
2017-08-12 23:06:07,929 - pw-logger - ERROR - PWControl.__init__(): lastlog mac not found in circles
2017-08-12 23:06:07,929 - pw-logger - DEBUG - mac -000D6F000072893C- logaddr -0- logaddr_idx -0- logaddr_ts -0-
2017-08-12 23:06:07,929 - pw-logger - ERROR - PWControl.__init__(): lastlog mac not found in circles
2017-08-12 23:06:07,929 - pw-logger - DEBUG - mac -000D6F0000768B61- logaddr -0- logaddr_idx -0- logaddr_ts -0-
2017-08-12 23:06:07,930 - pw-logger - ERROR - PWControl.__init__(): lastlog mac not found in circles
2017-08-12 23:06:07,934 - pw-logger - DEBUG - read_schedules
2017-08-12 23:06:07,934 - pw-logger - INFO - generate schedule: __PW2PY__test-alternate
2017-08-12 23:06:07,935 - pw-logger - INFO - generate schedule: __PW2PY__test-10
2017-08-12 23:06:07,935 - pw-logger - INFO - import   schedule: winter.json
2017-08-12 23:06:07,936 - pw-logger - INFO - import   schedule: carcharging.json
2017-08-12 23:06:07,936 - pw-logger - INFO - import   schedule: testsched1.json
2017-08-12 23:06:07,936 - pw-logger - INFO - import   schedule: testsched2.json
2017-08-12 23:06:07,937 - pw-logger - DEBUG - poll_configuration()
2017-08-12 23:06:07,937 - pw-logger - DEBUG - read_apply_controls
2017-08-12 23:06:07,937 - pw-logger - INFO - COMMU with str() True
2017-08-12 23:06:07,937 - pw-logger - INFO - COMMU with u True
2017-08-12 23:06:07,937 - pw-logger - DEBUG - circle mac: 000D6F00007293e5 before1 - state [r,sw,sc] ? on off - scname
2017-08-12 23:06:07,938 - pw-logger - DEBUG - circle mac: 000D6F00007293E5 before2 - state [r,sw,sc] ? ? ?
2017-08-12 23:06:07,941 - pw-logger - DEBUG - circle mac: 000D6F00007293e5 after1 - state [r,sw,sc] ? on off - scname
2017-08-12 23:06:07,941 - pw-logger - DEBUG - circle mac: 000D6F00007293E5 after2 - state [r,sw,sc] ? ? ?
2017-08-12 23:06:07,942 - pw-logger - DEBUG - SEND   30 '\x05\x05\x03\x030023000D6F00007293E562B2\r\n'
2017-08-12 23:06:07,959 - pw-logger - DEBUG - STRU      '-->>' '0000' '0024' <data> '56FA' '<---'
2017-08-12 23:06:07,959 - pw-logger - DEBUG - DATA    4 '00C1'
2017-08-12 23:06:07,960 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2017-08-12 23:06:07,963 - pw-logger - DEBUG - STRU      '--->' '0000' '0024' <data> 'FC5C' '<---'
2017-08-12 23:06:07,964 - pw-logger - DEBUG - DATA    4 '00E1'
2017-08-12 23:06:07,964 - pw-logger - ERROR - unexpected response [1]:'expected response code 0024, received code 0000'
2017-08-12 23:06:07,964 - pw-logger - DEBUG - STRU      '--->' '0000' '0024' <data> 'FC5C' '<---'
2017-08-12 23:06:07,964 - pw-logger - DEBUG - DATA    4 '00E1'
2017-08-12 23:06:07,964 - pw-logger - DEBUG - PARS      '00E1' EVAL '225'
2017-08-12 23:06:07,965 - pw-logger - DEBUG - Received an error status '00E1' from circle 'circle+' - Network slow or circle offline - Retry receive ...
2017-08-12 23:06:07,965 - pw-logger - DEBUG - SEND   16 '\x05\x05\x03\x030008014068\r\n'
2017-08-12 23:06:07,976 - pw-logger - DEBUG - STRU      '-->>' '0000' '0025' <data> 'FCAB' '<---'
2017-08-12 23:06:07,976 - pw-logger - DEBUG - DATA    4 '00C1'
2017-08-12 23:06:07,977 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
```

communications log:
```2017-08-12 23:06:06,111 - pwcomm - logging started
2017-08-12 23:06:07,881 - pwcomm - SEND   14 ---> 000A                             B43C <---
2017-08-12 23:06:07,890 - pwcomm - RECV   22 ---> 0000 0022 00C1 ................  9B7F <---
2017-08-12 23:06:07,900 - pwcomm - RECV   60 ---> 0011 0022 .... 000D6F000072A8CB 0101550D6F00007293E53D55FF 5986 <---
2017-08-12 23:06:07,901 - pwcomm - SEND   30 ---> 0023           000D6F00007293E5  62B2 <---
2017-08-12 23:06:07,909 - pwcomm - RECV   22 -->> 0000 0023 00C1 ................  312E <---
2017-08-12 23:06:07,926 - pwcomm - DTRC   91 '# APSRequestNodeInfo: Source MAC: 000D6F000072A8CB# APSRequestNodeInfo: Destination MAC: \r\n'
2017-08-12 23:06:07,926 - pwcomm - DSHR   18 '000D6F00007293E5\r\n'
2017-08-12 23:06:07,927 - pwcomm - RECV   22 ---> 0000 0023 00E1 ................  9B88 <---
2017-08-12 23:06:07,942 - pwcomm - SEND   30 ---> 0023           000D6F00007293E5  62B2 <---
2017-08-12 23:06:07,959 - pwcomm - RECV   22 -->> 0000 0024 00C1 ................  56FA <---
2017-08-12 23:06:07,961 - pwcomm - DTRC   91 '# APSRequestNodeInfo: Source MAC: 000D6F000072A8CB# APSRequestNodeInfo: Destination MAC: \r\n'
2017-08-12 23:06:07,963 - pwcomm - DSHR   18 '000D6F00007293E5\r\n'
2017-08-12 23:06:07,964 - pwcomm - RECV   22 ---> 0000 0024 00E1 ................  FC5C <---
2017-08-12 23:06:07,965 - pwcomm - SEND   16 ---> 0008                            01 4068 <---
2017-08-12 23:06:07,976 - pwcomm - RECV   22 -->> 0000 0025 00C1 ................  FCAB <---
2017-08-12 23:06:13,984 - pwcomm - TOUT    1 '\x83' - <!> Timeout on serial port
```

**Comment by gruijter** [comment]
You might want to first build a network using the (MS Windows) Plugwise Source software. Maybe the circles need a firmware update, or they need to have a factory reset before they can be linked to the stick. After you have built a successful network using Source, you can then switch to plugwise-2-py knowing that the circles and stick do work correctly.

**Comment by SevenW** [comment]
Plugwise-2-py is able to pair new devices once they are added to the configuration json files. It may take several hours or several reboots before they appear.

Most problems with inability to pair seem to originate form the difficult reset procedure of Plugwise.
