### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'write'

### ISSUE THREAD

**Issue by MagnusThome** [SevenW/Plugwise-2-py#49]
I deleted:
/home/pi/Plugwise-2-py
/home/pi/datalog
/home/pi/pwlog
/tmp/*

Reinstalled. I thought maybe it went wrong because maybe I started it manually once as root, not 100% sure. But I did look everywhere for file permissions but it was all the right owner, group and write permissions. Anyhow, after deleting and reinstalling, still the same error.

The *only* thing I carried over was the three settings files in config/pw-*.json
[pw-hostconfig.txt](https://github.com/SevenW/Plugwise-2-py/files/1750662/pw-hostconfig.txt)
[pw-control.txt](https://github.com/SevenW/Plugwise-2-py/files/1750663/pw-control.txt)
[pw-control.txt](https://github.com/SevenW/Plugwise-2-py/files/1750664/pw-control.txt)

```Feb 23 06:16:39 raspberrypi systemd[1]: Reloading.
Feb 23 06:16:40 raspberrypi systemd[1]: Reloading.
Feb 23 06:16:42 raspberrypi systemd[1]: Started Plugwise.
Feb 23 06:16:43 raspberrypi systemd[1]: Reloading.
Feb 23 06:16:45 raspberrypi python[1904]: rsync: link_stat "/home/pi/datalog/2018/pwact/pwact-2018-02-23*.log" failed: No such file or directory (2)
Feb 23 06:16:45 raspberrypi python[1904]: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Feb 23 06:16:45 raspberrypi systemd[1]: Started Plugwise Web.
Feb 23 06:17:01 raspberrypi CRON[1971]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Feb 23 06:17:27 raspberrypi kernel: [53626.228413] TCP: request_sock_TCP: Possible SYN flooding on port 8000. Sending cookies.  Check SNMP counters.
Feb 23 06:21:24 raspberrypi python[1904]: True
Feb 23 06:21:24 raspberrypi python[1904]: rsync -aXuq /home/pi/datalog/2018/pwact/pwact-2018-02-23*.log /tmp/2018/pwact/
Feb 23 06:21:24 raspberrypi python[1904]: Traceback (most recent call last):
Feb 23 06:21:24 raspberrypi python[1904]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1468, in <module>
Feb 23 06:21:24 raspberrypi python[1904]:     main.run()
Feb 23 06:21:24 raspberrypi python[1904]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1425, in run
Feb 23 06:21:24 raspberrypi python[1904]:     self.log_recording(self.controls[idx], c.mac)
Feb 23 06:21:24 raspberrypi python[1904]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1072, in log_recording
Feb 23 06:21:24 raspberrypi python[1904]:     f.write("%s, %s, %s\n" % (ts_str, watt, watt_hour))
Feb 23 06:21:24 raspberrypi python[1904]: AttributeError: 'NoneType' object has no attribute 'write'
Feb 23 06:21:24 raspberrypi systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Feb 23 06:21:24 raspberrypi systemd[1]: plugwise.service: Unit entered failed state.
Feb 23 06:21:24 raspberrypi systemd[1]: plugwise.service: Failed with result 'exit-code'.
Feb 23 06:21:24 raspberrypi systemd[1]: Stopping Plugwise Web...
Feb 23 06:21:24 raspberrypi systemd[1]: Stopped Plugwise Web.
pi@raspberrypi:~/Plugwise-2-py $

**Comment by MagnusThome** [comment]
Added logfiles too to first post

**Comment by SevenW** [comment]
The problem is a write to file problem. I assume that Plugwise-2-py was unable to open (create) a datalog file and then the subsequent write fails, because the file handle f = None.

Can you check permissions for the datalog folder? And see under which user plugwise-2-py runs?

ls -al /home/pi/datalog
ps -AF | grep Plugwise

**Comment by MagnusThome** [comment]
```
pi@raspberrypi:~ $ ps -AF | grep Plugwise
pi         601     1 49  6139 11312   0 19:14 ?        00:00:02 /usr/bin/python /home/pi/Plugwise-2-py/Plugwise-2.py
pi         620     1 21  8457 11272   0 19:14 ?        00:00:01 /usr/bin/python /home/pi/Plugwise-2-py/Plugwise-2-web.py
pi         656   553  0  1091  2100   0 19:14 pts/0    00:00:00 grep --color=auto Plugwise


ls -al /home/pi/datalog
total 32
drwxr-xr-x 5 pi pi 4096 Feb 23 06:18 .
drwxr-xr-x 6 pi pi 4096 Feb 23 19:06 ..
drwxr-xr-x 4 pi pi 4096 Feb 23 06:18 2011
drwxr-xr-x 4 pi pi 4096 Feb 23 06:18 2012
drwxr-xr-x 4 pi pi 4096 Feb 23 06:16 2018
-rw-r--r-- 1 pi pi  435 Feb 23 19:05 pwlastlog.log
-rw-r--r-- 1 pi pi 7021 Feb 23 19:04 pw-statusdump.json


pi@raspberrypi:~ $ cat /etc/systemd/system/plugwise.service
[Unit]
Description=Plugwise
After=network.target

[Service]
Type=simple
User=pi
ExecStart=/usr/bin/python /home/pi/Plugwise-2-py/Plugwise-2.py
WorkingDirectory=/home/pi/Plugwise-2-py

[Install]
WantedBy=multi-user.target

pi@raspberrypi:~ $ cat /etc/systemd/system/plugwise-web.service
[Unit]
Description=Plugwise Web
After=network.target plugwise.service
BindsTo=plugwise.service

[Service]
Type=simple
User=pi
ExecStart=/usr/bin/python /home/pi/Plugwise-2-py/Plugwise-2-web.py
WorkingDirectory=/home/pi/Plugwise-2-py

[Install]
WantedBy=multi-user.target

**Comment by MagnusThome** [comment]
```
pi@raspberrypi:~ $ ls -l
total 20
drwxr-xr-x  2 pi pi 4096 Feb 23 19:18 copiesconfig
drwxr-xr-x  5 pi pi 4096 Feb 23 06:18 datalog
drwxr-xr-x 12 pi pi 4096 Feb 23 06:13 Plugwise-2-py
drwxr-xr-x  2 pi pi 4096 Feb 23 19:14 pwlog
-rwxr-xr-x  1 pi pi  241 Feb 22 13:55 restartPlugwise2py.sh


pi@raspberrypi:~ $ cat restartPlugwise2py.sh
sudo systemctl stop plugwise.service
sudo systemctl start plugwise.service
sudo systemctl stop plugwise-web.service
sudo systemctl start plugwise-web.service
sudo systemctl status plugwise.service
sudo systemctl status plugwise-web.service

**Comment by MagnusThome** [comment]
I did a chmod -R ugo+w on both datalog and pwlog, didn't make any difference.



But this message pops up each time I start the kit... is this right, there is no such file on the disk:
```
Feb 24 20:10:52 raspberrypi systemd[1]: Started Plugwise Web.
Feb 24 20:10:54 raspberrypi python[1093]: rsync: link_stat "/home/pi/datalog/2018/pwact/pwact-2018-02-24*.log" failed: No such file or directory (2)
Feb 24 20:10:54 raspberrypi python[1093]: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender

**Comment by MagnusThome** [comment]
Aaahhhhhh! I found that in addition to the Circles and the Cirlce+ the Sticks ID was also in the pw-conf.json and pw-control.json files. Sorry about that. After fixing that I restarted everything and... now I get another errror. Ooops.

Soooo, I thought, just to be safe, I erase everything. Plugwise-2-py/, pwlog/, datalog/ and the stuff in /tmp. Reinstalled from scratch from github. Only saved the three pw-.json config files. But no, still get the same "new" error message.

[pw-conf.txt](https://github.com/SevenW/Plugwise-2-py/files/1755221/pw-conf.txt)
[pw-control.txt](https://github.com/SevenW/Plugwise-2-py/files/1755222/pw-control.txt)
[pw-hostconfig.txt](https://github.com/SevenW/Plugwise-2-py/files/1755223/pw-hostconfig.txt)

```
Feb 24 20:44:44 raspberrypi systemd[1]: Startup finished in 1.942s (kernel) + 23.958s (userspace) = 25.900s.
Feb 24 20:44:46 raspberrypi python[448]: rsync: link_stat "/home/pi/datalog/2018/pwact/pwact-2018-02-24*.log" failed: No such file or directory (2)
Feb 24 20:44:46 raspberrypi python[448]: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Feb 24 20:44:46 raspberrypi python[448]: True
Feb 24 20:44:46 raspberrypi python[448]: rsync -aXuq /home/pi/datalog/2018/pwact/pwact-2018-02-24*.log /tmp/2018/pwact/
Feb 24 20:44:46 raspberrypi python[448]: Traceback (most recent call last):
Feb 24 20:44:46 raspberrypi python[448]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1467, in <module>
Feb 24 20:44:46 raspberrypi python[448]:     main=PWControl()
Feb 24 20:44:46 raspberrypi python[448]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 158, in __init__
Feb 24 20:44:46 raspberrypi python[448]:     sconf = json.load(open(self.staticconfig_fn))
Feb 24 20:44:46 raspberrypi python[448]:   File "/usr/lib/python2.7/json/__init__.py", line 291, in load
Feb 24 20:44:46 raspberrypi python[448]:     **kw)
Feb 24 20:44:46 raspberrypi python[448]:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
Feb 24 20:44:46 raspberrypi python[448]:     return _default_decoder.decode(s)
Feb 24 20:44:46 raspberrypi python[448]:   File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
Feb 24 20:44:46 raspberrypi python[448]:     raise ValueError(errmsg("Extra data", s, end, len(s)))
Feb 24 20:44:46 raspberrypi python[448]: ValueError: Extra data: line 1 column 9 - line 12 column 1 (char 8 - 1427)
Feb 24 20:44:46 raspberrypi systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 20:44:46 raspberrypi systemd[1]: plugwise.service: Unit entered failed state.
Feb 24 20:44:46 raspberrypi systemd[1]: plugwise.service: Failed with result 'exit-code'.
Feb 24 20:44:46 raspberrypi systemd[1]: Stopping Plugwise Web...
Feb 24 20:44:46 raspberrypi systemd[1]: Stopped Plugwise Web.

**Comment by MagnusThome** [comment]
```
pi@raspberrypi:~ $ ls -laR datalog/
datalog/:
total 12
drwxr-xr-x 3 pi pi 4096 Feb 24 20:43 .
drwxr-xr-x 7 pi pi 4096 Feb 24 20:45 ..
drwxr-xr-x 4 pi pi 4096 Feb 24 20:43 2018

datalog/2018:
total 16
drwxr-xr-x 4 pi pi 4096 Feb 24 20:43 .
drwxr-xr-x 3 pi pi 4096 Feb 24 20:43 ..
drwxr-xr-x 2 pi pi 4096 Feb 24 20:43 pwact
drwxr-xr-x 2 pi pi 4096 Feb 24 20:43 pwlog

datalog/2018/pwact:
total 8
drwxr-xr-x 2 pi pi 4096 Feb 24 20:43 .
drwxr-xr-x 4 pi pi 4096 Feb 24 20:43 ..

datalog/2018/pwlog:
total 8
drwxr-xr-x 2 pi pi 4096 Feb 24 20:43 .
drwxr-xr-x 4 pi pi 4096 Feb 24 20:43 ..
pi@raspberrypi:~ $ ls -laR pwlog/
pwlog/:
total 24
drwxr-xr-x 2 pi pi 4096 Feb 24 20:43 .
drwxr-xr-x 7 pi pi 4096 Feb 24 20:45 ..
-rw-r--r-- 1 pi pi 1068 Feb 24 20:44 pw-communication.log
-rw-r--r-- 1 pi pi 4773 Feb 24 20:44 pw-logger.log
-rw-r--r-- 1 pi pi 1763 Feb 24 20:44 pw-web.log

**Comment by SevenW** [comment]
I was quite puzzled by the previous erro. I will try to understand why the write error is generated. The new error is luckely very simple.

The file pw-conf.json does no longer contain valid json. Easy to make mistakes. You need to add a '{' right at the start of the file:

```json
{
	"static": [{
			"mac": "000D6F00004BF6F1",
			"category": "misc",
			"name": "circle+",
			"loginterval": "60",
			"always_on": "False",
			"production": "False",
			"location": "default"
		},
```

**Comment by MagnusThome** [comment]
Oh! That's embarrasing. Thank you! Fixed that and *that* errormessage is gone. But the previous error message is back. The kit starts up and runs but if I turn someting off or on it crashes with the old message again:

```
Feb 24 22:13:25 raspberrypi python[442]: rsync -aXuq /home/pi/datalog/2018/pwact/pwact-2018-02-24*.log /tmp/2018/pwact/
Feb 24 22:13:25 raspberrypi python[442]: Traceback (most recent call last):
Feb 24 22:13:25 raspberrypi python[442]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1468, in <module>
Feb 24 22:13:25 raspberrypi python[442]:     main.run()
Feb 24 22:13:25 raspberrypi python[442]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1425, in run
Feb 24 22:13:25 raspberrypi python[442]:     self.log_recording(self.controls[idx], c.mac)
Feb 24 22:13:25 raspberrypi python[442]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1072, in log_recording
Feb 24 22:13:25 raspberrypi python[442]:     f.write("%s, %s, %s\n" % (ts_str, watt, watt_hour))
Feb 24 22:13:25 raspberrypi python[442]: AttributeError: 'NoneType' object has no attribute 'write'
Feb 24 22:13:25 raspberrypi systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 22:13:25 raspberrypi systemd[1]: plugwise.service: Unit entered failed state.
Feb 24 22:13:25 raspberrypi systemd[1]: plugwise.service: Failed with result 'exit-code'.
Feb 24 22:13:25 raspberrypi systemd[1]: Stopping Plugwise Web...
Feb 24 22:13:25 raspberrypi systemd[1]: Stopped Plugwise Web.

**Comment by SevenW** [comment]
I still do not get the root cause. So privileges seems to be OK. Old folders owned by pi, and it runs as user pi.

I would have expected that files are already created in /home/pi/datalog/2018/pwlog. But that seems to be empty. Strange.

Can you run plugwise-2-py with more logging? Please add this to the pw-hostconfig.json file:
"log_level": "debug", "log_comm": "yes"

**Comment by SevenW** [comment]
... and see whether you can create a file in the logfolder?
make sure you are logged in as user pi.

touch /home/pi/datalog/2018/pwlog/testfile.txt
ls -al /home/pi/datalog/2018/pwlog/

**Comment by MagnusThome** [comment]
> I would have expected that files are already created in /home/pi/datalog/2018/pwlog. But that seems to be empty. Strange.

I've deleted everything and reinstalled a number of times, so this is right after one of them I suppose. But is it logical according to the code that the directory is created at a different time as the logfile? Since the directory is there but not any files.

There are no problems writing to the directories, I even did a "chmod -R ugo+w" as user pi (not using sudo) which changed all the files and folders properly. And even with those rights I get the crash. 

Could it be something with the rights of the USB stick? Why I ask is because it's a fresh install on the Pi. The only special stuff on it is mosquitto and a usbip server sharing some other usb items but not the stick for Plugwise-2-py.


```
pi@raspberrypi:~ $ touch /home/pi/datalog/2018/pwlog/testfile.txt
pi@raspberrypi:~ $ ls -al /home/pi/datalog/2018/pwlog/
total 36
drwxr-xr-x 2 pi pi 4096 Feb 26 07:36 .
drwxr-xr-x 4 pi pi 4096 Feb 24 20:43 ..
-rw-r--r-- 1 pi pi 2295 Feb 24 22:11 pw-000D6F0000769270.log
-rw-r--r-- 1 pi pi 3285 Feb 25 22:00 pw-000D6F000076966C.log
-rw-r--r-- 1 pi pi 3330 Feb 25 22:00 pw-000D6F000076B2D1.log
-rw-r--r-- 1 pi pi 3330 Feb 25 22:00 pw-000D6F000076B583.log
-rw-r--r-- 1 pi pi 3330 Feb 25 22:49 pw-000D6F000076B926.log
-rw-r--r-- 1 pi pi 3015 Feb 25 22:49 pw-000D6F000076B9E1.log
-rw-r--r-- 1 pi pi 3330 Feb 25 22:49 pw-000D6F000076CE72.log
-rw-r--r-- 1 pi pi    0 Feb 26 07:36 testfile.txt

**Comment by MagnusThome** [comment]
I'm using another SD-card doing a 100% fresh install of raspbian on it, adding Plugwise2py first without usbip at all.

**Comment by MagnusThome** [comment]
Nope.

Brand new from scratch on a Rpi Zero using 2017-11-29-raspbian-stretch-lite

sudo apt-get update -y && sudo apt-get upgrade -y
sudo shutdown -r now
sudo apt-get install git -y
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
git clone https://github.com/SevenW/Plugwise-2-py.git
cd Plugwise-2-py
sudo pip install .

- added cricles to pw-control.json and pw-conf.json
- didn't do anything in raspi-config yet
- added the two systemd files for auto starting at boot

The only thing that is special to this install are my control.json and conf.json?

[pw-control.txt](https://github.com/SevenW/Plugwise-2-py/files/1757764/pw-control.txt)
[pw-conf.txt](https://github.com/SevenW/Plugwise-2-py/files/1757765/pw-conf.txt)


```
Feb 26 08:48:15 raspberrypi python[429]: rsync -aXuq /home/pi/datalog/2018/pwact/pwact-2018-02-26*.log /tmp/2018/pwact/
Feb 26 08:48:15 raspberrypi python[429]: Traceback (most recent call last):
Feb 26 08:48:15 raspberrypi python[429]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1468, in <module>
Feb 26 08:48:15 raspberrypi python[429]:     main.run()
Feb 26 08:48:15 raspberrypi python[429]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1425, in run
Feb 26 08:48:15 raspberrypi python[429]:     self.log_recording(self.controls[idx], c.mac)
Feb 26 08:48:15 raspberrypi python[429]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1072, in log_recording
Feb 26 08:48:15 raspberrypi python[429]:     f.write("%s, %s, %s\n" % (ts_str, watt, watt_hour))
Feb 26 08:48:15 raspberrypi python[429]: AttributeError: 'NoneType' object has no attribute 'write'
Feb 26 08:48:15 raspberrypi systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 08:48:15 raspberrypi systemd[1]: plugwise.service: Unit entered failed state.
Feb 26 08:48:15 raspberrypi systemd[1]: plugwise.service: Failed with result 'exit-code'.
Feb 26 08:48:15 raspberrypi systemd[1]: Stopping Plugwise Web...
Feb 26 08:48:15 raspberrypi systemd[1]: Stopped Plugwise Web.

**Comment by SevenW** [comment]
I think my initial analysis is flawed. I assumed that f.write raised the exception because I assumed that f = None. It may however be that one of the parameters to be written is None.

That is why I like to see logging with the log levels increased.
>Can you run plugwise-2-py with more logging? Please add this to the pw-hostconfig.json file:
"log_level": "debug", "log_comm": "yes"

**Comment by MagnusThome** [comment]
Yes, added that. Will run some tests and add results here shortly :-)

**Comment by MagnusThome** [comment]
One of the Circles has a file size of zero, maybe that's normal but I thought I'd show you anyway :-)

```
datalog/2018/pwact:
total 40
drwxr-xr-x 2 pi pi 4096 Feb 26 09:00 .
drwxr-xr-x 4 pi pi 4096 Feb 26 08:41 ..
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F00004BF6F1.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F0000769270.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F00007693DC.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F000076966C.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F000076B2D1.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F000076B583.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F000076B926.log
-rw-r--r-- 1 pi pi    0 Feb 26 08:59 pwact-2018-02-26-000D6F000076B9E1.log
-rw-r--r-- 1 pi pi   21 Feb 26 09:00 pwact-2018-02-26-000D6F000076CE72.log

datalog/2018/pwlog:
total 36
drwxr-xr-x 2 pi pi 4096 Feb 26 08:47 .
drwxr-xr-x 4 pi pi 4096 Feb 26 08:41 ..
-rw-r--r-- 1 pi pi 3780 Feb 26 08:46 pw-000D6F0000769270.log
-rw-r--r-- 1 pi pi 3825 Feb 26 10:05 pw-000D6F000076966C.log
-rw-r--r-- 1 pi pi 3870 Feb 26 10:04 pw-000D6F000076B2D1.log
-rw-r--r-- 1 pi pi 3870 Feb 26 10:04 pw-000D6F000076B583.log
-rw-r--r-- 1 pi pi 3870 Feb 26 10:04 pw-000D6F000076B926.log
-rw-r--r-- 1 pi pi 3555 Feb 26 10:04 pw-000D6F000076B9E1.log
-rw-r--r-- 1 pi pi 3870 Feb 26 10:04 pw-000D6F000076CE72.log

**Comment by MagnusThome** [comment]
[pwlastlog.log](https://github.com/SevenW/Plugwise-2-py/files/1758044/pwlastlog.log)
[pw-statusdump.json.txt](https://github.com/SevenW/Plugwise-2-py/files/1758045/pw-statusdump.json.txt)
[pw-communication.log](https://github.com/SevenW/Plugwise-2-py/files/1758046/pw-communication.log)
[pw-logger.log](https://github.com/SevenW/Plugwise-2-py/files/1758047/pw-logger.log)
[pw-web.log](https://github.com/SevenW/Plugwise-2-py/files/1758048/pw-web.log)
[pw-000D6F000076B9E1.log](https://github.com/SevenW/Plugwise-2-py/files/1758049/pw-000D6F000076B9E1.log)
[pw-000D6F000076CE72.log](https://github.com/SevenW/Plugwise-2-py/files/1758050/pw-000D6F000076CE72.log)

**Comment by SevenW** [comment]
Something must be broken with the debug log. Communication log seems to be OK but stops 2 minutes before the crash. Debug is not activated. Can you check whether the json syntax is correct?

I think I will build some exception handling around the offending line and then try to log the parameters.

**Comment by MagnusThome** [comment]
Looks right AFAIK:

{"permanent_path": "/home/pi/datalog", "tmp_path": "/tmp", "log_path": "/home/pi/pwlog", "serial": "/dev/ttyUSB0", "log_format": "epoch", "log_level": "debug", "log_comm": "yes"}

**Comment by MagnusThome** [comment]
Should I change the two log settings in pw-control.json too?

**Comment by SevenW** [comment]
I guess so. Please try.

**Comment by MagnusThome** [comment]
So what should I set them to?


PS:
It's a bit baffling, I'm worried I've missed something extremely obvious, since it obviously should work on a fresh install of Raspbian.  Well well, we'll see if it gets embarrasing for me in the end hahaha.

**Comment by MagnusThome** [comment]
Restarted a few times, went to the wbe page that first shows up but then it crashes.

[plugwise.zip](https://github.com/SevenW/Plugwise-2-py/files/1758699/plugwise.zip)

**Comment by SevenW** [comment]
Fully figured out the bug that has been bothering you for the last few days. The web i/f thing that yuo now report might be something different. To resolve the first bug try this:

change line 1031 in Plugwise-2.py
https://github.com/SevenW/Plugwise-2-py/blob/75f57ce28fe536d8d666161d94694e21e3538fc8/Plugwise-2.py#L1031

From
```python
            prev_dt = datetime.now()-timedelta(days=2000)
```
```python
            prev_dt = datetime.date(2000,1,1)
```

Take care of indentation in python. Needs to be all spaces (at leaset equal to the line above) (in case you are not fluent in python).

I have never considered the situation that a circle was not used (disconnected for over 2000 days (5.5 years). As 5.5 years ago is 2012, and the logging it reads is from 2012, the code decides that the file is already open, so skips this step.

After you have demonstrated this fiix to work (or not), try to find a stacktrace of the other crash you see with the web i/f

**Comment by MagnusThome** [comment]
Sorry, I was probably a bit muddy and unclear. The web page shows up when the Pi is freshly booted. But when I turn a circle off I can see in the Pi that the Plugwise-2.py has exited with the no attribute error. So the Plugwise-2-web.py has also stopped since it's dependent. What happens on the web page is... nothing :-) If I push any switch, nothing happens. Of course. There's no visible "crash" with the web page. If I refresh the browser I get nothing of course since the webserver is stopped.

Now off to try your fix!!! :-D

**Comment by MagnusThome** [comment]
```
Feb 26 14:00:55 raspberrypi python[881]: Traceback (most recent call last):
Feb 26 14:00:55 raspberrypi python[881]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1469, in <module>
Feb 26 14:00:55 raspberrypi python[881]:     main.run()
Feb 26 14:00:55 raspberrypi python[881]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1426, in run
Feb 26 14:00:55 raspberrypi python[881]:     self.log_recording(self.controls[idx], c.mac)
Feb 26 14:00:55 raspberrypi python[881]:   File "/home/pi/Plugwise-2-py/Plugwise-2.py", line 1032, in log_recording
Feb 26 14:00:55 raspberrypi python[881]:     prev_dt = datetime.date(2000,1,1)
Feb 26 14:00:55 raspberrypi python[881]: TypeError: descriptor 'date' requires a 'datetime.datetime' object but received a 'int'
Feb 26 14:00:55 raspberrypi systemd[1]: plugwise.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 14:00:55 raspberrypi systemd[1]: plugwise.service: Unit entered failed state.
Feb 26 14:00:55 raspberrypi systemd[1]: plugwise.service: Failed with result 'exit-code'.
Feb 26 14:00:55 raspberrypi systemd[1]: Stopping Plugwise Web...
Feb 26 14:00:55 raspberrypi systemd[1]: Stopped Plugwise Web.

**Comment by MagnusThome** [comment]
Changed to 
prev_dt = datetime.datetime.date(2000,1,1)
and the crash is no more I think.

**Comment by MagnusThome** [comment]
Seems there is no crash with this:

prev_dt = datetime(2000,1,1)

**Comment by SevenW** [comment]
The namespace prefixes is always a gamble in python.

**Comment by MagnusThome** [comment]
Oh yeah :-D

**Comment by MagnusThome** [comment]
This actually popped up after a while on the other server, impressive save from 18 years ago!

cat datalog/2000/pwlog/pw-000D6F000076CAAA.log
946681320,          0.0381,       6058.7736

**Comment by SevenW** [comment]
I think I know how that occurs. I expect that time stamp happened at your place and not the previous owner (but who knows). 

I discovered a problem after power outage. At recovery of a power outage, my internet connection is slow to come up again. Plugwise is already startup without the odroid in my case having no clue of the actual date and time. So at startup it sets the clock of all circles to whatever the default in linux is, which may be 1-1-2000?

I am going to think of a way to avoid this problem. The minimum is that I do not set time to circles if it can be distrusted, but also the logging to pwact files will get wrong timestamps, and that is more difficult to settle.

**Comment by SevenW** [comment]
Finally pushed the solution to github. See https://github.com/SevenW/Plugwise-2-py/commit/a97ab1eea9830ced66f269a84ad80bfeb434067a.
