### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by meden199** [SevenW/Plugwise-2-py#54]
I followd every step but when I start the web interface by starting:

nohup python Plugwise-2-web.py 8000 secure plugwise:mysecret >>pwwebout.log&
or
nohup python Plugwise-2-web.py >>pwwebout.log&

The webinterface does not start.

In the pwwebout.log:
`nohup: ignoring input
Traceback (most recent call last):
  File "Plugwise-2-web.py", line 51, in <module>
    cfg = json.load(open("pw-hostconfig.json"))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 165 (char 164)`

What am I doing wrong?

**Comment by meden199** [comment]
I missed a ,
Problem Solved
