### ISSUE TITLE
Exception while communicating

### ISSUE THREAD

**Issue by xander2k** [SevenW/Plugwise-2-py#9]
Hi,
my first circle+ is communicating but not full.
It syncs the time, but the command to switch on or off will crash the programm after a few seconds, every time, also after 10 times.

Its bad that the program crashes and it doesn't try again randomly.

Here is the output
Traceback (most recent call last):
  File "Plugwise-2.py", line 1331, in <module>
    main.run()
  File "Plugwise-2.py", line 1209, in run
    self.device.enable_joining(True)
  File "/server/PlugwisePy/Plugwise-2-py/plugwise/api.py", line 237, in enable_joining
    self.expect_response(PlugwiseAckMacResponse)
  File "/server/PlugwisePy/Plugwise-2-py/plugwise/api.py", line 149, in expect_response
    msg = self._recv_response(retry_timeout)
  File "/server/PlugwisePy/Plugwise-2-py/plugwise/api.py", line 105, in _recv_response
    raise TimeoutException("Timeout while waiting for response from device")
plugwise.exceptions.TimeoutException: Timeout while waiting for response from device
1442008872: Socket error on client Plugwise-2-py2960, disconnecting.

#############
the logfile will give this output
015-09-12 00:01:06,233 - pw-logger - DEBUG - circle mac: 000D6F0000B8111E before1 - state [r,sw,sc] on on off - scname
2015-09-12 00:01:06,234 - pw-logger - DEBUG - circle mac: 000D6F0000B8111E before2 - state [r,sw,sc] on ? off
2015-09-12 00:01:06,234 - pw-logger - INFO - circle mac: 000D6F0000B8111E needs to be switched on
2015-09-12 00:01:06,234 - pw-logger - INFO - API  000D6F0000B8111E Amiga circle switch: on
2015-09-12 00:01:06,234 - pw-logger - DEBUG - SEND   32 '\x05\x05\x03\x030017000D6F0000B8111E01CD4D\r\n'
2015-09-12 00:01:06,241 - pw-logger - DEBUG - STRU      '--->' '0000' '006E' <data> 'E78C' '<---'
2015-09-12 00:01:06,241 - pw-logger - DEBUG - DATA    4 '00C1'
2015-09-12 00:01:06,241 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2015-09-12 00:01:06,354 - pw-logger - DEBUG - STRU      '-->>' '0000' '006E' <data> '5F6C' '<---'
2015-09-12 00:01:06,354 - pw-logger - DEBUG - DATA   20 '00D8000D6F0000B8111E'
2015-09-12 00:01:06,354 - pw-logger - DEBUG - PARS      '00D8' EVAL '216'
2015-09-12 00:01:06,354 - pw-logger - DEBUG - PARS      '000D6F0000B8111E' EVAL '000D6F0000B8111E'
2015-09-12 00:01:06,354 - pw-logger - DEBUG - circle mac: 000D6F0000B8111E after1 - state [r,sw,sc] on on off - scname
2015-09-12 00:01:06,354 - pw-logger - DEBUG - circle mac: 000D6F0000B8111E after2 - state [r,sw,sc] on on off
2015-09-12 00:01:06,355 - pw-logger - DEBUG - SEND   30 '\x05\x05\x03\x03003E000D6F0000B8111EBB52\r\n'
2015-09-12 00:01:06,362 - pw-logger - DEBUG - STRU      '--->' '0000' '006F' <data> '095E' '<---'
2015-09-12 00:01:06,362 - pw-logger - DEBUG - DATA    4 '00C1'
2015-09-12 00:01:06,362 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2015-09-12 00:01:06,577 - pw-logger - DEBUG - STRU      '-->>' '003F' '006F' <data> '69D5' '<---'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - DATA   14 '1701060401457A'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '17' EVAL '23'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '01' EVAL '1'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '06' EVAL '6'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '170106' EVAL '23:01:06'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '04' EVAL '4'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '01' EVAL '1'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - PARS      '457A' EVAL '17786'
2015-09-12 00:01:06,578 - pw-logger - DEBUG - Circle Amiga get clock to 23:01:06
2015-09-12 00:01:06,578 - pw-logger - INFO - sync_time: circle Amiga time is 23:01:06
2015-09-12 00:01:06,579 - pw-logger - DEBUG - Circle Amiga set clock to 2015-09-11T23:01:06.579052
2015-09-12 00:01:06,579 - pw-logger - DEBUG - SEND   54 '\x05\x05\x03\x030016000D6F0000B8111E0F093DA5FFFFFFFF1701060403F9\r\n'
2015-09-12 00:01:06,588 - pw-logger - DEBUG - STRU      '--->' '0000' '0070' <data> '9CFD' '<---'
2015-09-12 00:01:06,588 - pw-logger - DEBUG - DATA    4 '00C1'
2015-09-12 00:01:06,588 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2015-09-12 00:01:06,640 - pw-logger - DEBUG - MQTT publish: plugwise2py/state/circle/000D6F0000B8111E {"powerts": 0, "name": "Amiga", "schedule": "off", "power1s": 0.0, "switchreq": "on", "readonly": false, "interval": 120, "switch": "on", "mac": "000D6F0000B8111E", "production": false, "monitor": false, "lastseen": 1442008866, "power1h": 0.0, "online": true, "savelog": false, "type": "circle", "schedname": "", "power8s": 0.0, "location": "hall"} retain = True
2015-09-12 00:01:06,640 - pw-logger - DEBUG - MQTT published message sequence number: 2
2015-09-12 00:01:06,679 - pw-logger - DEBUG - STRU      '-->>' '0000' '0070' <data> 'ED47' '<---'
2015-09-12 00:01:06,680 - pw-logger - DEBUG - DATA   20 '00D7000D6F0000B8111E'
2015-09-12 00:01:06,681 - pw-logger - DEBUG - PARS      '00D7' EVAL '215'
2015-09-12 00:01:06,681 - pw-logger - DEBUG - PARS      '000D6F0000B8111E' EVAL '000D6F0000B8111E'
2015-09-12 00:01:06,682 - pw-logger - DEBUG - SEND   30 '\x05\x05\x03\x030023000D6F0000B8111E7328\r\n'
2015-09-12 00:01:06,688 - pw-logger - DEBUG - STRU      '--->' '0000' '0071' <data> '36AC' '<---'
2015-09-12 00:01:06,688 - pw-logger - DEBUG - DATA    4 '00C1'
2015-09-12 00:01:06,689 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'
2015-09-12 00:01:06,787 - pw-logger - DEBUG - STRU      '-->>' '0024' '0071' <data> '563D' '<---'
2015-09-12 00:01:06,787 - pw-logger - DEBUG - DATA   42 '0F093DA5000446F801856539070140234E0844C202'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '0F' EVAL '2015'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '09' EVAL '9'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '3DA5' EVAL '15781'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '0F093DA5' EVAL '2015-09-11 23:01:00'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '000446F8' EVAL '55'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '01' EVAL '1'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '85' EVAL '133'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '653907014023' EVAL '653907014023'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '4E0844C2' EVAL '2011-06-27 10:52:18'
2015-09-12 00:01:06,788 - pw-logger - DEBUG - PARS      '02' EVAL '2'
2015-09-12 00:01:06,789 - pw-logger - DEBUG - SEND   16 '\x05\x05\x03\x030008014068\r\n'
2015-09-12 00:01:06,794 - pw-logger - DEBUG - STRU      '--->' '0000' '0072' <data> 'D87E' '<---'
2015-09-12 00:01:06,794 - pw-logger - DEBUG - DATA    4 '00C1'
2015-09-12 00:01:06,795 - pw-logger - DEBUG - PARS      '00C1' EVAL '193'

**Comment by SevenW** [comment]
I have added exception handling to catch the timeout exception, so the program does not crash anymore.

The timeout may be caused by a bad communication between Stick and Circle+.
If the Circle+ is too distant form the Stick, then also all other circles are difficult to reach. If you keep experiencing those timeouts (Circle+ offline) then move it closer to the Stick.

SevenW
